services:
  postgres:
    image: "postgres:17"
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=newsletter
  app:
    build: .
    ports:
      - 8000:8000
    develop:
      watch:
        - action: rebuild
          path: .
          target: /app
