application:
  host: 0.0.0.0
  port: 8000
  base_url: http://localhost:8000
database:
  host: postgres
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "newsletter"
email_client:
  sender_email: cndoit18@outlook.com
  timeout_milliseconds: 10000
  email_service:
    smtp:
      host: mailtutan
      port: 1025
