name: dagger
on: push
jobs:
  ci:
    name: ci
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Test
        uses: dagger/dagger-for-github@v7
        with:
          version: "latest"
          call: test
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
      - name: FormatCheck
        uses: dagger/dagger-for-github@v7
        with:
          version: "latest"
          call: format-check
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
      - name: Clippy
        uses: dagger/dagger-for-github@v7
        with:
          version: "latest"
          call: clippy
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
      - name: Audit
        uses: dagger/dagger-for-github@v7
        with:
          version: "latest"
          call: audit
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
